from .eleccion_serializer import EleccionSerializer
from .seccion_serializer import SeccionSerializer
from .cargo_serializer import CargoSerializer
from .recinto_seralizer import RecintoSerializer
from .mesa_serializer import MesaSerializer
from .votante_serializer import VotanteSerializer
from .jurado_seralizer import JuradoSerializer
from .partido_serializer import PartidoSerializer
from .candidato_serializer import CandidatoSerializer
from .papeleta_serializer import PapeletaSerializer
