# Generated by Django 5.2.3 on 2025-07-03 05:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Votante1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('foto_ci_anverso', models.ImageField(upload_to='ci/anverso/')),
                ('foto_votante', models.ImageField(upload_to='votantes/fotos/')),
                ('recinto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admElec.recinto1')),
            ],
        ),
    ]
