from .eleccion import Eleccion
from .seccion import Seccion
from .cargo import Cargo
from .recinto import Recinto
from .mesa import Mesa
from .votante import Votante
from .jurado import Jurado
from .partido import Partido
from .candidato import Candidato
from .papeleta import Papeleta