from .eleccion_viewset import EleccionViewSet
from .seccion_viewset import SeccionViewSet
from .cargo_viewset import CargoViewSet
from .recinto_viewset import RecintoViewSet
from .mesa_viewset import MesaViewSet
from .votante_viewset import VotanteViewSet
from .jurado_viewset import JuradoViewSet
from .partido_viewset import PartidoViewSet
from .candidato_viewset import CandidatoViewSet
from .papeleta_viewset import PapeletaViewSet
